name: Send Garbage Collection notifications
on:
  workflow_dispatch:
  schedule:
    # Run every day at 17:30 UTC -> 19:30 CET
    - cron: "30 17 * * *"

jobs:
  send-notification:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      SLW4A_CHAT_ID: ${{ secrets.SLW4A_CHAT_ID }}
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Berlin"
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.3"
          cache: "pip"
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Crawl AWG
        run: python crawl.py
